# Generated by Django 4.2.7 on 2023-12-02 20:44

import django.core.validators
from django.db import migrations, models
import utils.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "brand_code",
                    models.CharField(
                        max_length=5, unique=True, verbose_name="Brand Code"
                    ),
                ),
                ("title", models.CharField(max_length=124, verbose_name="Title")),
                ("term", models.TextField(blank=True, null=True, verbose_name="Term")),
                (
                    "shape",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Shape"
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        blank=True, max_length=64, null=True, verbose_name="Dose"
                    ),
                ),
                (
                    "price_exchange_subsidy",
                    utils.db.fields.PriceField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Total Price Including Foreign Exchange Subsidy",
                    ),
                ),
                (
                    "percent_share_of_organization_exchange_subsidy",
                    utils.db.fields.PercentField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Percent Share Of The Organization Including Foreign Exchange Subsidy",
                    ),
                ),
            ],
            options={
                "ordering": ["create_at"],
                "abstract": False,
            },
        ),
    ]
